### ISSUE TITLE
error in train

### ISSUE THREAD

**Issue by AmeenAli** [jonathanking/protein-transformer#12]
hello
i get the following error while training : 
`Traceback (most recent call last):
  File "train.py", line 681, in <module>
    main()
  File "train.py", line 676, in main
    device, args, log_writer, scheduler, drmsd_worker_pool)
  File "train.py", line 149, in train
    pool=drmsd_worker_pool)
  File "train.py", line 50, in train_epoch
    pred, tgt_crds, step, validation_datasets, model, device)
  File "/media/data2/ameenali/protein-transformer/protein_transformer/log.py", line 199, in do_train_batch_logging
    commit=False, log_angs=False, struct_name=f"V{split}")
  File "/media/data2/ameenali/protein-transformer/protein_transformer/log.py", line 340, in log_structure_and_angs
    gltf_out_path = os.path.join(args.gltf_dir, f"{wandb.run.step:05}_{struct_name}.gltf")
AttributeError: 'RunManaged' object has no attribute 'step'
`
any idea?

**Comment by jonathanking** [comment]
Hi, thanks for reaching out. This seems to be an issue with `wandb`. What version are you using, and have you tried updated `wandb`?
