### ISSUE TITLE
train with some error?

### ISSUE THREAD

**Issue by HadXu** [jonathanking/protein-transformer#9]
`[ Epoch 0 ]
  - (Train) drmsd=16.16, lndrmsd=0.0587509, rmse=0.4618, c=12.13, res/s=258:   0%|                                    | 0/996 [00:07<?, ?batch/s]
PyMOL not running, entering library mode (experimental)
Traceback (most recent call last):
  File "train.py", line 624, in <module>
    main()
  File "train.py", line 619, in main
    device, args, log_writer, scheduler, drmsd_worker_pool)
  File "train.py", line 148, in train
    pool=drmsd_worker_pool)
  File "train.py", line 49, in train_epoch
    pred, tgt_crds, step, validation_datasets, model, device)
  File "/data2/hadxu/protein-transformer/protein_transformer/log.py", line 199, in do_train_batch_logging
    commit=False, log_angs=False, struct_name=f"V{split}")
  File "/data2/hadxu/protein-transformer/protein_transformer/log.py", line 345, in log_structure_and_angs
    pse_out_path=f"{cur_struct_path}/{wandb.run.step:05}_both.pse")
  File "/data2/hadxu/protein-transformer/protein_transformer/protein/PDB_Creator.py", line 196, in save_gltfs
    pymol.cmd.save(gltf_out_path, f"{wandb.run.step:05}.gltf")
  File "/data2/hadxu/anaconda3/envs/py36/lib/python3.6/site-packages/pymol/exporting.py", line 892, in save
    raise pymol.CmdException('File format not supported for export')
pymol.CmdException:  Error: File format not supported for export`

thank you!

**Comment by jonathanking** [comment]
Hi! This error is because you are attempting to export a GLTF file (a kind of 3D file for visualizing protein structure) with PyMOL, but your version of PyMOL doesn't support this. 

If you are using `conda` to manage your environments, you can install the correct version of PyMOL, along with a GLTF converter, with the following command. Be aware that this version of PyMOL is not considered free. 

`conda install -c schrodinger schrodinger/label/alpha::pymol collada2gltf`

You may also build PyMOL from source https://pymolwiki.org/index.php/Linux_Install#Updating.
